services:
    app:
        image: my-laravel-app
        secrets:
            - yandex_client_id
            - yandex_client_secret
            - pastebin_api_key
        environment:
            YANDEX_CLIENT_ID_FILE: /run/secrets/yandex_client_id
            YANDEX_CLIENT_SECRET_FILE: /run/secrets/yandex_client_secret
            PASTEBIN_API_KEY_FILE: /run/secrets/pastebin_api_key
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - mysql
        networks:
            - laravel

    webserver:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pastebin_test
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mysql
        networks:
            - laravel

volumes:
    mysql_data:

secrets:
    yandex_client_id:
        external: true
    yandex_client_secret:
        external: true
    pastebin_api_key:
        external: true

networks:
    laravel:
        external: true
