<div class="my-3 p-3 bg-body rounded-3">
    <h6 class="border-bottom pb-2 mb-0"><ya-tr-span data-index="19-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Recent updates" data-translation="Последние обновления" data-ch="0" data-type="trSpan" style="visibility: inherit !important;">Последние public пасты</ya-tr-span></h6>
    <div class="d-flex text-body-secondary pt-3">
        <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
        <p class="pb-3 mb-0 small lh-sm border-bottom">
            <strong class="d-block text-gray-dark"><ya-tr-span data-index="20-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="@username" data-translation="@имя_пользователя" data-ch="0" data-type="trSpan" style="visibility: inherit !important;">@имя_пользователя</ya-tr-span></strong><ya-tr-span data-index="20-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value=" Some representative placeholder content, with some information about this user. " data-translation=" Некоторый репрезентативный контент-заполнитель с некоторой информацией об этом пользователе. " data-ch="0" data-type="trSpan" style="visibility: inherit !important;"> Некоторый репрезентативный контент-заполнитель с некоторой информацией об этом пользователе. </ya-tr-span><ya-tr-span data-index="20-1" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Imagine this being some sort of status update, perhaps? " data-translation="Представьте, что это какое-то обновление статуса, возможно? " data-ch="0" data-type="trSpan" style="visibility: inherit !important;">Представьте, что это какое-то обновление статуса, возможно?  </ya-tr-span></p>
    </div>
    <div class="d-flex text-body-secondary pt-3">
        <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#e83e8c"></rect><text x="50%" y="50%" fill="#e83e8c" dy=".3em">32x32</text></svg>
        <p class="pb-3 mb-0 small lh-sm border-bottom">
            <strong class="d-block text-gray-dark"><ya-tr-span data-index="21-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="@username" data-translation="@имя_пользователя" data-ch="0" data-type="trSpan" style="visibility: inherit !important;">@имя_пользователя</ya-tr-span></strong><ya-tr-span data-index="21-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value=" Some more representative placeholder content, related to this other user. " data-translation=" Ещё один пример заполнителя, связанный с этим другим пользователем. " data-ch="0" data-type="trSpan" style="visibility: inherit !important;">  Ещё один пример заполнителя, связанный с этим другим пользователем. </ya-tr-span><ya-tr-span data-index="21-1" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Another status update, perhaps. " data-translation="Возможно, ещё одно обновление статуса. " data-ch="0" data-type="trSpan" style="visibility: inherit !important;">Возможно, ещё одно обновление статуса.  </ya-tr-span></p>
    </div>
    <div class="d-flex text-body-secondary pt-3">
        <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#6f42c1"></rect><text x="50%" y="50%" fill="#6f42c1" dy=".3em">32x32</text></svg>
        <p class="pb-3 mb-0 small lh-sm border-bottom">
            <strong class="d-block text-gray-dark"><ya-tr-span data-index="22-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="@username" data-translation="@имя_пользователя" data-ch="0" data-type="trSpan" style="visibility: inherit !important;">@имя_пользователя</ya-tr-span></strong><ya-tr-span data-index="22-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value=" This user also gets some representative placeholder content. " data-translation=" Этот пользователь также получает некоторое количество репрезентативного контента. " data-ch="0" data-type="trSpan" style="visibility: inherit !important;"> Этот пользователь также получает некоторое количество репрезентативного контента. </ya-tr-span><ya-tr-span data-index="22-1" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="Maybe they did something interesting, and you really want to highlight this in the recent updates. " data-translation="Возможно, он сделал что-то интересное, и вы действительно хотите выделить это в последних обновлениях. " data-ch="0" data-type="trSpan" style="visibility: inherit !important;">Возможно, он сделал что-то интересное, и вы действительно хотите выделить это в последних обновлениях.  </ya-tr-span></p>
    </div>
    <small class="d-block text-end mt-3">
        <a href="#"><ya-tr-span data-index="23-0" data-translated="true" data-source-lang="en" data-target-lang="ru" data-value="All updates" data-translation="Все обновления" data-ch="0" data-type="trSpan" style="visibility: inherit !important;">Все обновления</ya-tr-span></a>
    </small>
</div>
